name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs['src-tauri--release_created'] }}
      tag_name: ${{ steps.release.outputs['src-tauri--tag_name'] }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # Trigger the release build when a new version is published
  build:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
    permissions:
      contents: write
